# MULTI DIMENSIONAL ARRAY

In [80]:
import numpy as np

In [81]:
a_2d=np.array([[10,20,30],[23,55,15]])

In [82]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [83]:
a_2d.shape

(2, 3)

In [84]:
a_2d.ndim

2

In [85]:
a_2d.size

6

In [86]:
a_2d.dtype

dtype('int64')

In [87]:
a_2d[0]

array([10, 20, 30])

In [88]:
a_2d[1]

array([23, 55, 15])

# ANOTHER TYPE OF MULTI DIMESIONAL ARRAY

In [89]:
another_type_array=np.array([[[1,2,3,4]]])

In [90]:
another_type_array

array([[[1, 2, 3, 4]]])

In [91]:
another_type_array.shape

(1, 1, 4)

In [92]:
another_type_array.ndim

3

In [93]:
another_type_array.size

4

In [94]:
another_type_array[0]

array([[1, 2, 3, 4]])

# ACCESS ELEMENTS IN MULTI DIMENSIONAL ARRAY

In [95]:
#FIRST ELEMENT IN FIRST ARRAY
a_2d=np.array([[10,20,30],[23,55,15]])
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [96]:
a_2d[0][0]

np.int64(10)

In [97]:
#SECOND ELEMENT IN FIRST ARRAY
a_2d[0][1]

np.int64(20)

In [98]:
#THIRD ELEMENT IN FIRST ARRAY
a_2d[0][2]

np.int64(30)

In [99]:
#FIRST ELEMENT IN SECOND ARRAY
a_2d[1][0]

np.int64(23)

In [100]:
#SECOND ELEMENT IN SECOND ARRAY
a_2d[1][1]

np.int64(55)

In [101]:
#THIRD ELEMENT IN SECOND ARRAY
a_2d[1][2]

np.int64(15)

# CHANGING DATA TYPE

In [102]:
a_2d.astype(float)

array([[10., 20., 30.],
       [23., 55., 15.]])

In [103]:
#another way(suitable to before the creation of array)
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [104]:
a_2d=np.array([[10,20,30],[23,55,15]], dtype=float)

In [105]:
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

# BIGGER ARRAY

In [106]:
a_bigger=np.array([
[
[10,20,30,40],[1,2,3,4],[5,6,7,8]
],
[
[5,10,15,20],[4,5,6,7],[11,22,33,44]
],
[
[55,66,77,88],[12,13,14,15],[50,60,70,80]
]
],dtype=float)

In [107]:
a_bigger

array([[[10., 20., 30., 40.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 5., 10., 15., 20.],
        [ 4.,  5.,  6.,  7.],
        [11., 22., 33., 44.]],

       [[55., 66., 77., 88.],
        [12., 13., 14., 15.],
        [50., 60., 70., 80.]]])

In [108]:
a_bigger.shape

(3, 3, 4)

In [109]:
a_bigger.ndim

3

In [110]:
a_bigger.size

36

In [111]:
#access elements 
a_bigger[0][1][3]

np.float64(4.0)

In [112]:
a_bigger[1][2][1]

np.float64(22.0)

In [113]:
a_bigger[2][0][2]

np.float64(77.0)

In [114]:
#access array
a_bigger[0][1]

array([1., 2., 3., 4.])

In [115]:
a_bigger[1][2]

array([11., 22., 33., 44.])

# FILLING ARRAY

In [116]:
np.full

<function numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)>

In [117]:
a_full=np.full((1,2,3,4),5)

In [118]:
a_full

array([[[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]]])

In [119]:
a_full.shape

(1, 2, 3, 4)

In [120]:
a_full.ndim

4

In [121]:
a_full.size

24

In [141]:
#3 array 5 row 4 column 15-fill
a_full=np.full((3,5,4),15)
a_full

array([[[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]]])

# ZEROS AND ONES

In [122]:
a_zeros=np.zeros((4,4))
a_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
a_zero=np.zeros((4,3))
a_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [123]:
b_ones=np.ones((3,4))
b_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [124]:
b_ones.shape

(3, 4)

In [125]:
b_ones.ndim

2

In [126]:
b_ones.size

12

In [127]:
b_ones[2][0]

np.float64(1.0)

In [143]:
a_one=np.ones((3,5,4))
a_one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# EMPTY AND RANDOM

In [140]:
e=np.empty((2,3))
e

array([[ 0.,  7., 14.],
       [21., 28., 35.]])

In [129]:
ar=np.random.random((2,3))
ar

array([[0.75971342, 0.2661453 , 0.75077986],
       [0.43009814, 0.23580126, 0.6836188 ]])

In [130]:
ar.shape

(2, 3)

In [131]:
ar.ndim

2

In [132]:
ar.size

6

# RANGES

### Arange

In [133]:
a_arange=np.arange(10,51,5)
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [148]:
#print odd numbers 1-20
oarange=np.arange(1,21,2)
oarange               

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [147]:
#print even numbers 1-30
earange=np.arange(2,31,2)
earange

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

### Linspace

In [134]:
a_linspace=np.linspace(0,35,6)
a_linspace

array([ 0.,  7., 14., 21., 28., 35.])

a_linspace.shape

In [135]:
a_linspace.ndim

1

In [136]:
a_linspace.size

6

In [137]:
a_space=np.linspace(2,10,5,dtype=int)
a_space

array([ 2,  4,  6,  8, 10])

In [151]:
a_space=np.linspace(1,10,5,dtype=int)
a_space

array([ 1,  3,  5,  7, 10])

# IDENTITY MATRIX

In [138]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [139]:
#another function
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])