# MATH FUNCTION/UNIVERSAL FUNCTIONS

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [5]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [6]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [7]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [8]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [9]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [10]:
np.abs(a)

array([1, 2, 3, 4, 5])

# AGGREGATE FUNCTION

In [10]:
a.sum()

np.int64(15)

In [11]:
a.min()

np.int64(1)

In [12]:
a.max()

np.int64(5)

In [13]:
a.mean()

np.float64(3.0)

In [14]:
np.median(a)

np.float64(3.0)

In [15]:
np.std(a)

np.float64(1.4142135623730951)

In [11]:
np.var(a)

np.float64(2.0)