# IMPORT NUMPY


In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [3]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
#find version of numpy
print(np.__version__)

2.3.5


# ARRAY SLICING

In [8]:
a=np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]


In [9]:
a=np.array([[10,20,30],
           [40,50,60]])
print(a[:,1:])

[[20 30]
 [50 60]]


# DATA TYPE

In [13]:
a=np.array([1,2,3],dtype=float)
print(a)
print(a.dtype)

[1. 2. 3.]
float64


# ARRAY RESHAPING

In [16]:
a=np.array([10,20,30,40,50,60])
print(a.reshape(3,2)) #reshape(row,column)

[[10 20]
 [30 40]
 [50 60]]


In [18]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a.reshape(6))

[1 2 3 4 5 6]


# RANDOM MODULE

In [28]:
np.random.seed(0)#using seed(0) for dont change random values

In [34]:
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [35]:
print(np.random.randint(1,11,5))

[6 3 5 8 7]


In [36]:
print(np.random.randn(4))

[-0.05503512 -0.10731045  1.36546718 -0.09769572]


In [37]:
print(np.random.choice([10,20,30,40],3))

[30 10 20]


# ARRAY ITERATING

In [40]:
a=np.array([1,2,3,4,5])
for i in a:
    print(i)

1
2
3
4
5


In [42]:
a=np.array([[10,20,30],
           [40,50,60]])
for i in np.nditer(a):
    print(i)

10
20
30
40
50
60


# JOINING ARRAYS

In [45]:
a=([1,2,3])
b=([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [46]:
#another methods for joining
#stack()_joining arrays vertically
#vstack()_joining arrays vertically
#hstack()_joing arrays horizontaly

### 1.stack()

In [48]:
a=([1,2,3])
b=([4,5,6])
print(np.stack((a,b)))

[[1 2 3]
 [4 5 6]]


### 2.vstack()

In [49]:
a=([1,2,3])
b=([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


### 3.hstack()

In [50]:
a=([1,2,3])
b=([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


# SPLITING OF ARRAYS

In [51]:
a=np.array([1,2,3,4,5])
print(np.array_split(a,2))

[array([1, 2, 3]), array([4, 5])]


# SEARCHING ARRAYS

In [52]:
a=np.array([10,20,30,40])
print(np.where(a==20))

(array([1]),)


In [53]:
a=np.array([10,20,30,40])
print(np.where(a==30))

(array([2]),)


In [54]:
a=np.array([10,20,30,20,40])
print(np.where(a==20))

(array([1, 3]),)


In [55]:
a=np.array([10,20,30,40])
print(np.where(a>20))

(array([2, 3]),)


# SORTING ARRAYS

In [56]:
a=np.array([40,60,30,20,10])
print(np.sort(a))

[10 20 30 40 60]


In [57]:
a=np.array(["banana","cherry","apple"])
print(np.sort(a))

['apple' 'banana' 'cherry']


# FILTER ARRAYS

In [58]:
a=np.array([40,60,30,20,10])
print(a[a>25])

[40 60 30]


In [59]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a%2==0])

[2 4 6]


In [60]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a%2!=0])

[1 3 5]


# ARRAY MATHEMATICS

In [61]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[   10   400 27000]


In [62]:
print(a*2)
print(a/2)
print(a**2)

[20 40 60]
[ 5. 10. 15.]
[100 400 900]


# AXIS CONCEPT

In [63]:
#axis=0(column)
#axis=1(row)
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[5 7 9]
[ 6 15]
