In [1]:
import numpy as np

In [2]:
#1. Create a NumPy array containing the numbers 10, 20, 30, 40, 50 .
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [5]:
#2. Create a NumPy array containing numbers from 1 to 10 .
a= np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#3. Create an array of even numbers between 1 and 20 .
a=np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
#4. Create an array of odd numbers between 1 and 20 .
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
#5. Create a NumPy array containing five zeros.
a=np.zeros(5,dtype=int)
a

array([0, 0, 0, 0, 0])

In [17]:
#6. Create a NumPy array containing six ones.
a=np.ones(6,dtype=int)
a

array([1, 1, 1, 1, 1, 1])

In [18]:
#7. Create a 2 × 3 NumPy array.
a=np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#8. Create a 3 × 3 NumPy array containing numbers from 1 to 9 .
a=np.array([[[1,2,3],
            [4,5,6],
             [7,8,9]]])
a
a.ndim  

#another way
z = np.arange(1,10).reshape(3,3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
#9. Create an array of five equally spaced numbers between 0 and 10 .
a=np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#10. Create an array containing the numbers 5, 10, 15, 20, 25 and print the first element
a=np.array([5, 10, 15, 20, 25])
print(a[0])

5


In [37]:
#11. Create an array containing 10, 20, 30, 40, 50 and print the last three elements
a=np.array([10, 20, 30, 40, 50])
print(a[2: ])


[30 40 50]


In [38]:
#12. Create an array from 1 to 10 and print only the numbers greater than 5 .
a=np.arange(1,11)
print(a[a>5])

[ 6  7  8  9 10]


In [40]:
#13. Create an array from 1 to 10 and print only the even numbers.
a=np.arange(1,11)
print(a[a%2==0])

[ 2  4  6  8 10]


In [42]:
#14. Create an array [10, 20, 30, 40, 50] and find its maximum value.
a=np.array([10, 20, 30, 40, 50])
print(max(a))

50


In [43]:
#15. Create an array [10, 20, 30, 40, 50] and find its minimum value.
a=np.array([10, 20, 30, 40, 50])
print(min(a))

10


In [44]:
#16. Create an array [10, 20, 30, 40, 50] and calculate its sum.
a=np.array([10, 20, 30, 40, 50])
print(sum(a))

150


In [45]:
#17. Create an array [10, 20, 30, 40, 50] and calculate its mean.
a=np.array([10, 20, 30, 40, 50])
print(a.mean())

30.0


In [48]:
#18. Create an array [5, 2, 8, 1, 9] and sort it in ascending order.
a=np.array([5, 2, 8, 1, 9])
print(np.sort(a))

[1 2 5 8 9]


In [54]:
#19. Create an array [10, 20, 30, 40, 50] and find the position of its maximum value 
a=np.array([10,20,30,40,50])
print(np.argmax(a))

4


In [55]:
#20. Create an array [10, 20, 30, 40, 50] and find the position of its minimum value
a=np.array([10,20,30,40,50])
print(np.argmin(a))

0
